// AUTO-GENERATED from the Apify actor IoSHqwTR9YGhzccez input schema. Do not edit by hand.
// Regenerate with: npx tsx src/scripts/gen-b2b-options.ts
import type { ScraperFormFieldOption } from '../types.js';

export const SENIORITY_OPTIONS: ScraperFormFieldOption[] = [
    { value: "founder", label: "Founder" },
    { value: "owner", label: "Owner" },
    { value: "c_suite", label: "C Suite" },
    { value: "director", label: "Director" },
    { value: "partner", label: "Partner" },
    { value: "vp", label: "Vp" },
    { value: "head", label: "Head" },
    { value: "manager", label: "Manager" },
    { value: "senior", label: "Senior" },
    { value: "entry", label: "Entry" },
    { value: "trainee", label: "Trainee" },
];

export const FUNCTIONAL_OPTIONS: ScraperFormFieldOption[] = [
    { value: "c_suite", label: "C Suite" },
    { value: "finance", label: "Finance" },
    { value: "product_management", label: "Product Management" },
    { value: "engineering", label: "Engineering" },
    { value: "design", label: "Design" },
    { value: "education", label: "Education" },
    { value: "human_resources", label: "Human Resources" },
    { value: "information_technology", label: "Information Technology" },
    { value: "legal", label: "Legal" },
    { value: "marketing", label: "Marketing" },
    { value: "operations", label: "Operations" },
    { value: "sales", label: "Sales" },
    { value: "support", label: "Support" },
];

export const COMPANY_SIZE_OPTIONS: ScraperFormFieldOption[] = [
    { value: "1-10", label: "1-10" },
    { value: "11-20", label: "11-20" },
    { value: "21-50", label: "21-50" },
    { value: "51-100", label: "51-100" },
    { value: "101-200", label: "101-200" },
    { value: "201-500", label: "201-500" },
    { value: "501-1000", label: "501-1000" },
    { value: "1001-2000", label: "1001-2000" },
    { value: "2001-5000", label: "2001-5000" },
    { value: "5001-10000", label: "5001-10000" },
    { value: "10001-20000", label: "10001-20000" },
    { value: "20001-50000", label: "20001-50000" },
    { value: "50000+", label: "50000+" },
];

export const EMAIL_STATUS_OPTIONS: ScraperFormFieldOption[] = [
    { value: "validated", label: "Validated" },
    { value: "not_validated", label: "Not Validated" },
    { value: "unknown", label: "Unknown" },
];

export const REVENUE_OPTIONS: ScraperFormFieldOption[] = [
    { value: "100K", label: "100K" },
    { value: "500K", label: "500K" },
    { value: "1M", label: "1M" },
    { value: "5M", label: "5M" },
    { value: "10M", label: "10M" },
    { value: "25M", label: "25M" },
    { value: "50M", label: "50M" },
    { value: "100M", label: "100M" },
    { value: "500M", label: "500M" },
    { value: "1B", label: "1B" },
    { value: "5B", label: "5B" },
    { value: "10B", label: "10B" },
];

export const FUNDING_OPTIONS: ScraperFormFieldOption[] = [
    { value: "seed", label: "Seed" },
    { value: "angel", label: "Angel" },
    { value: "series_a", label: "Series A" },
    { value: "series_b", label: "Series B" },
    { value: "series_c", label: "Series C" },
    { value: "series_d", label: "Series D" },
    { value: "series_e", label: "Series E" },
    { value: "series_f", label: "Series F" },
    { value: "venture_round", label: "Venture Round" },
    { value: "debt_financing", label: "Debt Financing" },
    { value: "convertible_note", label: "Convertible Note" },
    { value: "private_equity_round", label: "Private Equity Round" },
    { value: "other_round", label: "Other Round" },
];

export const INDUSTRY_OPTIONS: ScraperFormFieldOption[] = [
    { value: "information technology & services", label: "Information Technology & Services" },
    { value: "construction", label: "Construction" },
    { value: "marketing & advertising", label: "Marketing & Advertising" },
    { value: "real estate", label: "Real Estate" },
    { value: "health, wellness & fitness", label: "Health, Wellness & Fitness" },
    { value: "management consulting", label: "Management Consulting" },
    { value: "computer software", label: "Computer Software" },
    { value: "internet", label: "Internet" },
    { value: "retail", label: "Retail" },
    { value: "financial services", label: "Financial Services" },
    { value: "consumer services", label: "Consumer Services" },
    { value: "hospital & health care", label: "Hospital & Health Care" },
    { value: "automotive", label: "Automotive" },
    { value: "restaurants", label: "Restaurants" },
    { value: "education management", label: "Education Management" },
    { value: "food & beverages", label: "Food & Beverages" },
    { value: "design", label: "Design" },
    { value: "hospitality", label: "Hospitality" },
    { value: "accounting", label: "Accounting" },
    { value: "events services", label: "Events Services" },
    { value: "nonprofit organization management", label: "Nonprofit Organization Management" },
    { value: "entertainment", label: "Entertainment" },
    { value: "electrical/electronic manufacturing", label: "Electrical/electronic Manufacturing" },
    { value: "leisure, travel & tourism", label: "Leisure, Travel & Tourism" },
    { value: "professional training & coaching", label: "Professional Training & Coaching" },
    { value: "transportation/trucking/railroad", label: "Transportation/trucking/railroad" },
    { value: "law practice", label: "Law Practice" },
    { value: "apparel & fashion", label: "Apparel & Fashion" },
    { value: "architecture & planning", label: "Architecture & Planning" },
    { value: "mechanical or industrial engineering", label: "Mechanical Or Industrial Engineering" },
    { value: "insurance", label: "Insurance" },
    { value: "telecommunications", label: "Telecommunications" },
    { value: "human resources", label: "Human Resources" },
    { value: "staffing & recruiting", label: "Staffing & Recruiting" },
    { value: "sports", label: "Sports" },
    { value: "legal services", label: "Legal Services" },
    { value: "oil & energy", label: "Oil & Energy" },
    { value: "media production", label: "Media Production" },
    { value: "machinery", label: "Machinery" },
    { value: "wholesale", label: "Wholesale" },
    { value: "consumer goods", label: "Consumer Goods" },
    { value: "music", label: "Music" },
    { value: "photography", label: "Photography" },
    { value: "medical practice", label: "Medical Practice" },
    { value: "cosmetics", label: "Cosmetics" },
    { value: "environmental services", label: "Environmental Services" },
    { value: "graphic design", label: "Graphic Design" },
    { value: "business supplies & equipment", label: "Business Supplies & Equipment" },
    { value: "renewables & environment", label: "Renewables & Environment" },
    { value: "facilities services", label: "Facilities Services" },
    { value: "publishing", label: "Publishing" },
    { value: "food production", label: "Food Production" },
    { value: "arts & crafts", label: "Arts & Crafts" },
    { value: "building materials", label: "Building Materials" },
    { value: "civil engineering", label: "Civil Engineering" },
    { value: "religious institutions", label: "Religious Institutions" },
    { value: "public relations & communications", label: "Public Relations & Communications" },
    { value: "higher education", label: "Higher Education" },
    { value: "printing", label: "Printing" },
    { value: "furniture", label: "Furniture" },
    { value: "mining & metals", label: "Mining & Metals" },
    { value: "logistics & supply chain", label: "Logistics & Supply Chain" },
    { value: "research", label: "Research" },
    { value: "pharmaceuticals", label: "Pharmaceuticals" },
    { value: "individual & family services", label: "Individual & Family Services" },
    { value: "medical devices", label: "Medical Devices" },
    { value: "civic & social organization", label: "Civic & Social Organization" },
    { value: "e-learning", label: "E-learning" },
    { value: "security & investigations", label: "Security & Investigations" },
    { value: "chemicals", label: "Chemicals" },
    { value: "government administration", label: "Government Administration" },
    { value: "online media", label: "Online Media" },
    { value: "investment management", label: "Investment Management" },
    { value: "farming", label: "Farming" },
    { value: "writing & editing", label: "Writing & Editing" },
    { value: "textiles", label: "Textiles" },
    { value: "mental health care", label: "Mental Health Care" },
    { value: "primary/secondary education", label: "Primary/secondary Education" },
    { value: "broadcast media", label: "Broadcast Media" },
    { value: "biotechnology", label: "Biotechnology" },
    { value: "information services", label: "Information Services" },
    { value: "international trade & development", label: "International Trade & Development" },
    { value: "motion pictures & film", label: "Motion Pictures & Film" },
    { value: "consumer electronics", label: "Consumer Electronics" },
    { value: "banking", label: "Banking" },
    { value: "import & export", label: "Import & Export" },
    { value: "industrial automation", label: "Industrial Automation" },
    { value: "recreational facilities & services", label: "Recreational Facilities & Services" },
    { value: "performing arts", label: "Performing Arts" },
    { value: "utilities", label: "Utilities" },
    { value: "sporting goods", label: "Sporting Goods" },
    { value: "fine art", label: "Fine Art" },
    { value: "airlines/aviation", label: "Airlines/aviation" },
    { value: "computer & network security", label: "Computer & Network Security" },
    { value: "maritime", label: "Maritime" },
    { value: "luxury goods & jewelry", label: "Luxury Goods & Jewelry" },
    { value: "veterinary", label: "Veterinary" },
    { value: "venture capital & private equity", label: "Venture Capital & Private Equity" },
    { value: "wine & spirits", label: "Wine & Spirits" },
    { value: "plastics", label: "Plastics" },
    { value: "aviation & aerospace", label: "Aviation & Aerospace" },
    { value: "commercial real estate", label: "Commercial Real Estate" },
    { value: "computer games", label: "Computer Games" },
    { value: "packaging & containers", label: "Packaging & Containers" },
    { value: "executive office", label: "Executive Office" },
    { value: "computer hardware", label: "Computer Hardware" },
    { value: "computer networking", label: "Computer Networking" },
    { value: "market research", label: "Market Research" },
    { value: "outsourcing/offshoring", label: "Outsourcing/offshoring" },
    { value: "program development", label: "Program Development" },
    { value: "translation & localization", label: "Translation & Localization" },
    { value: "philanthropy", label: "Philanthropy" },
    { value: "public safety", label: "Public Safety" },
    { value: "alternative medicine", label: "Alternative Medicine" },
    { value: "museums & institutions", label: "Museums & Institutions" },
    { value: "warehousing", label: "Warehousing" },
    { value: "defense & space", label: "Defense & Space" },
    { value: "newspapers", label: "Newspapers" },
    { value: "paper & forest products", label: "Paper & Forest Products" },
    { value: "law enforcement", label: "Law Enforcement" },
    { value: "investment banking", label: "Investment Banking" },
    { value: "government relations", label: "Government Relations" },
    { value: "fund-raising", label: "Fund-raising" },
    { value: "think tanks", label: "Think Tanks" },
    { value: "glass, ceramics & concrete", label: "Glass, Ceramics & Concrete" },
    { value: "capital markets", label: "Capital Markets" },
    { value: "semiconductors", label: "Semiconductors" },
    { value: "animation", label: "Animation" },
    { value: "political organization", label: "Political Organization" },
    { value: "package/freight delivery", label: "Package/freight Delivery" },
    { value: "wireless", label: "Wireless" },
    { value: "international affairs", label: "International Affairs" },
    { value: "public policy", label: "Public Policy" },
    { value: "libraries", label: "Libraries" },
    { value: "gambling & casinos", label: "Gambling & Casinos" },
    { value: "railroad manufacture", label: "Railroad Manufacture" },
    { value: "ranching", label: "Ranching" },
    { value: "military", label: "Military" },
    { value: "fishery", label: "Fishery" },
    { value: "supermarkets", label: "Supermarkets" },
    { value: "dairy", label: "Dairy" },
    { value: "tobacco", label: "Tobacco" },
    { value: "shipbuilding", label: "Shipbuilding" },
    { value: "judiciary", label: "Judiciary" },
    { value: "alternative dispute resolution", label: "Alternative Dispute Resolution" },
    { value: "nanotechnology", label: "Nanotechnology" },
    { value: "agriculture", label: "Agriculture" },
    { value: "legislative office", label: "Legislative Office" },
];

export const LOCATION_OPTIONS: ScraperFormFieldOption[] = [
    { value: "united states", label: "United States" },
    { value: "germany", label: "Germany" },
    { value: "india", label: "India" },
    { value: "united kingdom", label: "United Kingdom" },
    { value: "russia", label: "Russia" },
    { value: "france", label: "France" },
    { value: "china", label: "China" },
    { value: "canada", label: "Canada" },
    { value: "netherlands", label: "Netherlands" },
    { value: "mexico", label: "Mexico" },
    { value: "belgium", label: "Belgium" },
    { value: "japan", label: "Japan" },
    { value: "brazil", label: "Brazil" },
    { value: "australia", label: "Australia" },
    { value: "poland", label: "Poland" },
    { value: "thailand", label: "Thailand" },
    { value: "sweden", label: "Sweden" },
    { value: "portugal", label: "Portugal" },
    { value: "spain", label: "Spain" },
    { value: "czech republic", label: "Czech Republic" },
    { value: "taiwan", label: "Taiwan" },
    { value: "south africa", label: "South Africa" },
    { value: "colombia", label: "Colombia" },
    { value: "italy", label: "Italy" },
    { value: "vietnam", label: "Vietnam" },
    { value: "nigeria", label: "Nigeria" },
    { value: "singapore", label: "Singapore" },
    { value: "hong kong", label: "Hong Kong" },
    { value: "ireland", label: "Ireland" },
    { value: "israel", label: "Israel" },
    { value: "switzerland", label: "Switzerland" },
    { value: "turkey", label: "Turkey" },
    { value: "romania", label: "Romania" },
    { value: "south korea", label: "South Korea" },
    { value: "indonesia", label: "Indonesia" },
    { value: "united arab emirates", label: "United Arab Emirates" },
    { value: "saudi arabia", label: "Saudi Arabia" },
    { value: "austria", label: "Austria" },
    { value: "philippines", label: "Philippines" },
    { value: "peru", label: "Peru" },
    { value: "malaysia", label: "Malaysia" },
    { value: "argentina", label: "Argentina" },
    { value: "ukraine", label: "Ukraine" },
    { value: "ghana", label: "Ghana" },
    { value: "denmark", label: "Denmark" },
    { value: "norway", label: "Norway" },
    { value: "finland", label: "Finland" },
    { value: "puerto rico", label: "Puerto Rico" },
    { value: "qatar", label: "Qatar" },
    { value: "macau", label: "Macau" },
    { value: "new zealand", label: "New Zealand" },
    { value: "hungary", label: "Hungary" },
    { value: "luxembourg", label: "Luxembourg" },
    { value: "kuwait", label: "Kuwait" },
    { value: "egypt", label: "Egypt" },
    { value: "slovakia", label: "Slovakia" },
    { value: "greece", label: "Greece" },
    { value: "kenya", label: "Kenya" },
    { value: "bulgaria", label: "Bulgaria" },
    { value: "costa rica", label: "Costa Rica" },
];
